# Dockerfile.dev
FROM node:18-alpine

WORKDIR /app

# Copy dependency files only to leverage Docker's cache
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Set the command to run the application in dev mode
CMD ["npm", "run", "dev"]