import { Fira_Code } from "next/font/google";
import "./globals.css";
import Nav from "@/sections/Nav";
import Footer from "@/components/Footer";

const fira_code = Fira_Code({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fira_code.className} bg-theme font-medium text-white`}
        style={{
          backgroundImage: "url('/bg.webp')",
          backgroundSize: "100%",
          backgroundRepeat: "repeat-y",
          backgroundPosition: "center top",
        }}
      >
        <Nav />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
